window.BOOKING_DATA = {
  bookings: [
    {
      id: "hotel-qinghai",
      stopIds: ["q1-3", "q2-1"],
      region: "qinggan",
      dayId: "qinggan-d1",
      status: "confirmed",
      date: "2026-09-24",
      dateLabel: { zh: "9月24–25日 · 1 晚", en: "Sep 24–25 · 1 night" },
      time: { zh: "入住 14:00 後 · 退房 12:00 前", en: "Check-in after 14:00 · Check-out before 12:00" },
      title: { zh: "青海湖卡巴倉·措瓊諾日野奢民宿", en: "Qinghai Lake Kabacang Cuoqiong Nuori" },
      titleKo: "Kabacang",
      platform: "待補",
      orderNo: "",
      voucherNo: "",
      qty: { zh: "1 晚 · 5人 · 房型待補", en: "1 night · 5 pax · room type TBD" },
      lead: "",
      howToUse: {
        zh: "二郎劍開車約 10–15 分 · 有製氧機／地暖 · 早餐約 08:00–10:00",
        en: "~10–15 min from Erlangjian · oxygen concentrators / floor heating · breakfast ~08:00–10:00",
      },
      address: {
        zh: "青海海南州共和縣江西溝鄉下社村五社 030",
        en: "No. 030, Wushe, Xiashe Village, Jiangxigou, Gonghe, Qinghai",
      },
      note: { zh: "湖邊夜間很冷 · 免費停車 · 可在民宿吃氂牛火鍋", en: "Cold lakeside nights · free parking · yak hotpot available" },
      link: "https://www.trip.com/hotels/gonghe-hotel-detail-63438619/",
      website: null,
      phone: "+86-137-3464-6936",
      amount: "",
    },
    {
      id: "hotel-dachaidan",
      stopIds: ["q2-4", "q3-1", "q3-5"],
      region: "qinggan",
      dayId: "qinggan-d2",
      status: "confirmed",
      date: "2026-09-25",
      dateLabel: { zh: "9月25–27日 · 2 晚", en: "Sep 25–27 · 2 nights" },
      time: { zh: "入住／退房時間以酒店為準", en: "Check-in / out per hotel" },
      title: { zh: "大柴旦麗呈翠星酒店", en: "Da Qaidam Rezen Cuixing Hotel" },
      titleKo: "Rezen Cuixing",
      platform: "待補",
      orderNo: "",
      voucherNo: "",
      qty: { zh: "2 晚 · 5人 · 房型待補", en: "2 nights · 5 pax · room type TBD" },
      lead: "",
      howToUse: {
        zh: "連住兩晚作西線基地 · 客房有製氧機／加濕器 · Day 3 早出晚歸",
        en: "Two-night west-loop base · in-room oxygen / humidifier · Day 3 out-and-back",
      },
      address: {
        zh: "青海海西州大柴旦鎮義海街 9 號",
        en: "9 Yihai Street, Da Qaidam Town, Haixi, Qinghai",
      },
      note: { zh: "鎮內可停 7 座 · 有餐廳／溫泉等配套", en: "7-seater parking in town · restaurant / hot spring on site" },
      link: null,
      website: "https://www.rezenqaidam.cn/",
      phone: "+86-977-745-6666",
      amount: "",
    },
    {
      id: "hotel-dunhuang",
      stopIds: ["q4-3", "q6-1"],
      region: "qinggan",
      dayId: "qinggan-d4",
      status: "confirmed",
      date: "2026-09-27",
      dateLabel: { zh: "9月27–29日 · 2 晚", en: "Sep 27–29 · 2 nights" },
      time: { zh: "入住／退房時間以民宿為準", en: "Check-in / out per stay" },
      title: { zh: "煌漠玥民宿 Moon Field（鳴沙山月牙泉店）", en: "Moon Field Homestay (Mingsha / Crescent Spring)" },
      titleKo: "Moon Field",
      platform: "待補",
      orderNo: "",
      voucherNo: "",
      qty: { zh: "2 晚 · 5人 · 房型待補", en: "2 nights · 5 pax · room type TBD" },
      lead: "",
      howToUse: {
        zh: "月牙泉鎮楊家橋 · Day 5 傍晚步行／短駛去鳴沙山 · 早赴莫高窟約 25–35 分",
        en: "Yangjiaqiao, Crescent Spring town · walk/short drive to Mingsha at sunset · ~25–35 min to Mogao in the morning",
      },
      address: {
        zh: "甘肅敦煌市月牙泉鎮鳴山路楊家橋三組 58 號",
        en: "58 Group 3, Yangjiaqiao, Mingshan Rd, Yueyaquan Town, Dunhuang",
      },
      note: { zh: "沙塵天關窗 · 不在沙洲夜市，晚餐在月牙泉鎮解決", en: "Close windows on dusty days · dinner in Yueyaquan Town, not Shazhou night market" },
      link: null,
      website: null,
      phone: "",
      amount: "",
    },
    {
      id: "hotel-zhangye",
      stopIds: ["q6-4", "q7-1"],
      region: "qinggan",
      dayId: "qinggan-d6",
      status: "confirmed",
      date: "2026-09-29",
      dateLabel: { zh: "9月29–30日 · 1 晚", en: "Sep 29–30 · 1 night" },
      time: { zh: "入住／退房時間以酒店為準", en: "Check-in / out per hotel" },
      title: { zh: "望山國際大酒店（張掖西站店）", en: "Wangshan International Hotel (Zhangye West Station)" },
      titleKo: "Wangshan",
      platform: "待補",
      orderNo: "",
      voucherNo: "",
      qty: { zh: "1 晚 · 5人 · 房型待補", en: "1 night · 5 pax · room type TBD" },
      lead: "",
      howToUse: {
        zh: "新墩鎮雙塔民俗文化村 · 近高速西出口／張掖西站 · 丹霞日落後約 40 分回到酒店",
        en: "Shuangta Folk Village, Xindun · near west expressway exit / Zhangye West Station · ~40 min after Danxia sunset",
      },
      address: {
        zh: "甘肅張掖市甘州區（新）墩鎮雙塔民俗文化村 2–3 號",
        en: "2–3 Shuangta Folk Culture Village, (Xin)dun Town, Ganzhou, Zhangye",
      },
      note: { zh: "不在甘州市中心 · 晚餐以酒店／新墩周邊為主", en: "Not downtown Ganzhou · dinner at the hotel or around Xindun" },
      link: "https://m.ctrip.com/html5/hotel/hoteldetail/110506085.html",
      website: null,
      phone: "+86-936-822-1111",
      amount: "",
    },
    {
      id: "hotel-qilian",
      stopIds: ["q7-3", "q8-1"],
      region: "qinggan",
      dayId: "qinggan-d7",
      status: "confirmed",
      date: "2026-09-30",
      dateLabel: { zh: "9月30日–10月1日 · 1 晚", en: "Sep 30–Oct 1 · 1 night" },
      time: { zh: "入住／退房時間以酒店為準", en: "Check-in / out per hotel" },
      title: { zh: "祁連五礦國貿飯店", en: "Qilian Minmetals International Hotel" },
      titleKo: "Minmetals Qilian",
      platform: "待補",
      orderNo: "",
      voucherNo: "",
      qty: { zh: "1 晚 · 5人 · 房型待補", en: "1 night · 5 pax · room type TBD" },
      lead: "",
      howToUse: {
        zh: "八寶鎮濱河路 · 縣城內 · 次日崗什卡→門源→西寧",
        en: "Binhe Rd, Babao Town · in the county seat · next day Gangshika → Menyuan → Xining",
      },
      address: {
        zh: "青海海北州祁連縣八寶鎮濱河路",
        en: "Binhe Road, Babao Town, Qilian County, Qinghai",
      },
      note: { zh: "海拔高、夜間冷 · 確認暖氣與熱水", en: "High and cold at night · confirm heat and hot water" },
      link: null,
      website: null,
      phone: "",
      amount: "",
    },
    {
      id: "hotel-xining",
      stopIds: ["q8-4"],
      region: "qinggan",
      dayId: "qinggan-d8",
      status: "confirmed",
      date: "2026-10-01",
      dateLabel: { zh: "10月1–2日 · 1 晚", en: "Oct 1–2 · 1 night" },
      time: { zh: "入住／退房時間以民宿為準", en: "Check-in / out per stay" },
      title: { zh: "記憶時光摩洛哥復古鏡民宿", en: "Memory Time Moroccan Mirror Homestay" },
      titleKo: "Memory Time",
      platform: "待補",
      orderNo: "",
      voucherNo: "",
      qty: { zh: "1 晚 · 5人 · 房型待補", en: "1 night · 5 pax · room type TBD" },
      lead: "",
      howToUse: {
        zh: "城東中發源城市廣場 9 棟 26 樓 1267 · 近東關 · 次日塔爾寺後約 16:00 出發趕 9C7396",
        en: "Rm 1267, 26F, Bldg 9, Zhongfayuan Plaza, Chengdong · near Dongguan · leave ~16:00 after Ta’er Si for 9C7396",
      },
      address: {
        zh: "青海西寧市城東區中發源城市廣場 9 棟 26 樓 1267 室",
        en: "Room 1267, 26F, Building 9, Zhongfayuan City Plaza, Chengdong, Xining",
      },
      note: { zh: "公寓民宿 · 確認電梯／停車 · 東關釀皮走路可達", en: "Apartment stay · confirm lift / parking · Dongguan niangpi is walkable" },
      link: null,
      website: null,
      phone: "",
      amount: "",
    },
    {
      id: "mogao-ticket",
      stopIds: ["q5-1"],
      region: "qinggan",
      dayId: "qinggan-d5",
      status: "pending",
      date: "2026-09-28",
      dateLabel: { zh: "9月28日", en: "Sep 28" },
      time: { zh: "建議上午場", en: "Morning session preferred" },
      title: { zh: "莫高窟門票（待預約）", en: "Mogao Caves tickets (to book)" },
      titleKo: "Mogao",
      platform: "敦煌研究院",
      orderNo: "",
      voucherNo: "",
      qty: { zh: "A 類票 ×5（實體窟+數字展示中心）", en: "Type A ×5 (caves + digital center)" },
      lead: "",
      howToUse: {
        zh: "官網／小程序提前預約（熱門日建議 15 天前）· 攜身份證／回鄉證入園 · 現場幾乎無票",
        en: "Book on the Academy site/app (≈15 days ahead in peak) · ID / Home Return Permit · almost no walk-up tickets",
      },
      address: { zh: "甘肅敦煌市莫高窟", en: "Mogao Caves, Dunhuang, Gansu" },
      note: { zh: "禁拍照閃光 · 跟講解員進入指定洞窟", en: "No flash · enter designated caves with a guide" },
      link: "https://ticket.dunhuang.org.cn/",
      website: "https://www.mogaoku.net/",
      phone: "",
      amount: "",
    },
  ],
};

window.bookingForStop = function (stopId) {
  return (window.BOOKING_DATA?.bookings || []).find((b) => (b.stopIds || []).includes(stopId));
};

