window.FLIGHT_DATA = {
  passengers: [],
  flights: [
    {
      id: "f1",
      date: "2026-09-24",
      dateLabel: { zh: "9月24日 · 四", en: "Thu · Sep 24" },
      airline: { zh: "春秋航空", en: "Spring Airlines" },
      flightNo: "9C7395",
      pnr: "",
      fareClass: null,
      cabin: { zh: "經濟艙", en: "Economy" },
      from: { code: "CAN", zh: "廣州白雲國際機場 T3", en: "Guangzhou Baiyun T3" },
      to: { code: "LHW", zh: "蘭州中川國際機場 T3", en: "Lanzhou Zhongchuan T3" },
      depart: "06:30",
      arrive: "09:40",
      checkInHint: { zh: "廉航建議 04:30 前到白雲 T3（起飛前約 2h）· 有托運須現場值機", en: "LCC: at Baiyun T3 by ~04:30 (≈2h before) · checked bags need counter check-in" },
      bagCarry: { zh: "手提額以春秋訂單為準（常為 8kg）· 托運待補", en: "Cabin bag per Spring booking (often 8kg) · checked bags TBD" },
      seats: [],
    },
    {
      id: "f1b",
      date: "2026-09-24",
      dateLabel: { zh: "9月24日 · 四 · 趙晨", en: "Thu · Sep 24 · Zhao Chen" },
      airline: { zh: "待補", en: "TBD" },
      flightNo: "待補",
      pnr: "",
      fareClass: null,
      cabin: { zh: "待補", en: "TBD" },
      from: { code: "—", zh: "出發地待補", en: "Origin TBD" },
      to: { code: "XNN", zh: "西寧曹家堡機場", en: "Xining Caojiabao" },
      depart: "—",
      arrive: "待補",
      checkInHint: { zh: "其餘人 09:40 中川落地取車，沿 G6 約 1.5–2h 來接 · 航班號／抵達時間貼上來即可對表", en: "The others land LHW 09:40, pick up the car, ~1.5–2h west on G6 · paste flight no. / arrival to lock the timing" },
      bagCarry: { zh: "待補", en: "TBD" },
      seats: [],
    },
    {
      id: "f2",
      date: "2026-10-02",
      dateLabel: { zh: "10月2日 · 五", en: "Fri · Oct 2" },
      airline: { zh: "春秋航空", en: "Spring Airlines" },
      flightNo: "9C7396",
      pnr: "",
      fareClass: null,
      cabin: { zh: "經濟艙", en: "Economy" },
      from: { code: "LHW", zh: "蘭州中川國際機場 T3", en: "Lanzhou Zhongchuan T3" },
      to: { code: "CAN", zh: "廣州白雲國際機場 T3", en: "Guangzhou Baiyun T3" },
      depart: "21:00",
      arrive: "00:15+1",
      checkInHint: { zh: "西寧約 16:00 出發 · 18:30 到中川 T3 還車 · 建議 19:00 前值機 · 國慶次日可能排隊", en: "Leave Xining ~16:00 · LHW T3 by 18:30 to return the car · check in by ~19:00 · National Day queues" },
      bagCarry: { zh: "手提額以春秋訂單為準（常為 8kg）· 托運待補", en: "Cabin bag per Spring booking (often 8kg) · checked bags TBD" },
      seats: [],
    },
  ],
};
