window.FOOD_DATA = {
  title: { zh: "青甘美食 List", en: "Qinghai–Gansu food list" },
  hint: {
    zh: "旅途彈性備選 · 點地址可開 Google Maps · 清真餐為主、口味偏牛羊",
    en: "Flexible picks · tap address for Maps · mostly Halal, lamb & beef",
  },
  places: [
    {
      id: "lanzhou-lamian",
      name: { zh: "蘭州牛肉麵（機場／市區）", en: "Lanzhou beef noodles" },
      nameKo: "Lanzhou lamian",
      category: { zh: "麵", en: "Noodles" },
      area: { zh: "蘭州", en: "Lanzhou" },
      address: "兰州中川国际机场 / 兰州市区",
      note: { zh: "Day 1 早班可在白雲吃一碗；中川取車後趕西寧接機，午餐可在曹家堡解決", en: "Day 1 early flight: a bowl at Baiyun; after LHW pickup, lunch can be at Xining Airport while waiting" },
      maps: "兰州牛肉面",
      dayHint: { zh: "適合 Day 1 落地或 Day 9 機場", en: "Fits Day 1 landing or Day 9 airport" },
    },
    {
      id: "qinghai-yogurt",
      name: { zh: "青海老酸奶", en: "Qinghai yogurt" },
      nameKo: "Qinghai yogurt",
      category: { zh: "小吃", en: "Snack" },
      area: { zh: "青海湖／西寧", en: "Qinghai Lake / Xining" },
      address: "青海湖景区 或 西宁水井巷",
      note: { zh: "高原腸胃先少量試 · 超市也有碗裝", en: "Try a little first at altitude · also sold in shops" },
      maps: "青海 老酸奶",
      dayHint: { zh: "Day 1 湖邊或 Day 8–9 西寧", en: "Day 1 lakeside or Day 8–9 Xining" },
    },
    {
      id: "chaka-lamb",
      name: { zh: "茶卡／烏蘭 手抓羊肉", en: "Chaka / Ulan hand-pulled lamb" },
      nameKo: "Hand-pulled lamb",
      category: { zh: "正餐", en: "Meal" },
      area: { zh: "茶卡鹽湖周邊", en: "Around Chaka" },
      address: "青海海西州乌兰县茶卡镇",
      note: { zh: "鹽湖風大易餓 · 午餐在鎮上清真館最穩", en: "Windy at the lake · a town Halal lunch is the safe pick" },
      maps: "茶卡镇 手抓羊肉",
      dayHint: { zh: "適合 Day 2 茶卡後", en: "Fits after Chaka on Day 2" },
      onItinerary: true,
    },
    {
      id: "dachaidan-halal",
      name: { zh: "大柴旦清真餐", en: "Da Qaidam Halal" },
      nameKo: "Da Qaidam Halal",
      category: { zh: "正餐", en: "Meal" },
      area: { zh: "大柴旦鎮", en: "Da Qaidam" },
      address: "青海海西州大柴旦镇",
      note: { zh: "鎮上選擇不多 · Day 3 長途請自備乾糧水果", en: "Few options in town · pack snacks for the long Day 3" },
      maps: "大柴旦镇 清真餐厅",
      dayHint: { zh: "Day 2 晚餐／Day 3 出發前", en: "Day 2 dinner / Day 3 breakfast" },
    },
    {
      id: "dunhuang-huangmian",
      name: { zh: "敦煌黃麵／驢肉黃麵", en: "Dunhuang yellow noodles" },
      nameKo: "Huangmian",
      category: { zh: "麵", en: "Noodles" },
      area: { zh: "敦煌市區／沙洲夜市", en: "Dunhuang / Shazhou night market" },
      address: "敦煌市沙洲夜市",
      note: { zh: "勁道寬麵配辣子 · Day 4 住月牙泉鎮，夜市較遠，晚餐就近；黃麵更適合 Day 5 莫高窟後進城", en: "Chewy wide noodles with chili · Day 4 stay is Yueyaquan Town (far from Shazhou); better as Day 5 lunch after Mogao" },
      maps: "敦煌 黄面 沙洲夜市",
      dayHint: { zh: "更適合 Day 5 莫高窟後午餐", en: "Better as Day 5 lunch after Mogao" },
      onItinerary: true,
    },
    {
      id: "zhaoji-noodles",
      name: { zh: "趙記手工掛麵（備選）", en: "Zhaoji handmade noodles (optional)" },
      nameKo: "Zhaoji",
      category: { zh: "麵", en: "Noodles" },
      area: { zh: "敦煌", en: "Dunhuang" },
      address: "敦煌市",
      note: { zh: "本地掛麵館 · 店址以地圖實時為準", en: "Local noodle house · confirm the latest pin on Maps" },
      maps: "敦煌 赵记手工挂面",
      dayHint: { zh: "適合 Day 5 莫高窟後午餐", en: "Fits Day 5 lunch after Mogao" },
    },
    {
      id: "jiayuguan-chuan",
      name: { zh: "嘉峪關烤肉／燒烤", en: "Jiayuguan barbecue" },
      nameKo: "Chuan / BBQ",
      category: { zh: "正餐", en: "Meal" },
      area: { zh: "嘉峪關", en: "Jiayuguan" },
      address: "嘉峪关市",
      note: { zh: "關城中午日照強 · 在市區或關城附近吃完再東行丹霞", en: "Harsh midday sun at the fort · eat in town then continue to Danxia" },
      maps: "嘉峪关 烤肉",
      dayHint: { zh: "適合 Day 6 嘉峪關中午", en: "Fits Day 6 lunch in Jiayuguan" },
    },
    {
      id: "zhangye-chaopao",
      name: { zh: "張掖炒炮", en: "Zhangye chaopao" },
      nameKo: "Chaopao",
      category: { zh: "麵", en: "Noodles" },
      area: { zh: "張掖市區", en: "Zhangye city" },
      address: "张掖市甘州区",
      note: { zh: "當地特色炒麵片 · 住西站望山，市區炒炮較遠，也可酒店／新墩解決", en: "Local stir-fried noodle squares · Wangshan is by West Station, not downtown — hotel / Xindun dinner also works" },
      maps: "张掖 炒炮",
      dayHint: { zh: "Day 6 晚餐可選 · 酒店離市區較遠", en: "Optional Day 6 dinner · hotel is not downtown" },
    },
    {
      id: "qilian-yak",
      name: { zh: "祁連氂牛肉／藏餐", en: "Qilian yak / Tibetan food" },
      nameKo: "Yak beef",
      category: { zh: "正餐", en: "Meal" },
      area: { zh: "祁連縣", en: "Qilian County" },
      address: "青海海北州祁连县",
      note: { zh: "高海拔少油少酒 · 熱湯麵更穩", en: "Go light at altitude · hot noodle soup is safer than heavy meals" },
      maps: "祁连县 牦牛肉",
      dayHint: { zh: "適合 Day 7 晚餐", en: "Fits Day 7 dinner" },
    },
    {
      id: "xining-niangpi",
      name: { zh: "西寧釀皮／甜醅", en: "Xining niangpi & sweet barley wine" },
      nameKo: "Niangpi / tianpei",
      category: { zh: "小吃", en: "Snack" },
      area: { zh: "西寧 · 水井巷／東關", en: "Xining · Shuijingxiang / Dongguan" },
      address: "西宁市城东区水井巷",
      note: { zh: "民宿在城東中發源廣場 · 東關釀皮走路可達 · 國慶人多", en: "Stay is at Zhongfayuan Plaza, Chengdong · Dongguan niangpi is walkable · crowded on National Day" },
      maps: "西宁 水井巷 酿皮",
      dayHint: { zh: "適合 Day 8 晚餐或 Day 9 午餐", en: "Fits Day 8 dinner or Day 9 lunch" },
      onItinerary: true,
    },
  ],
};
